trigger:
  - none

pool:
  vmImage: ubuntu-latest

variables:
  - name: WORKDIR
    value: "$(System.DefaultWorkingDirectory)/apis/user-java"
  - name: JAVA_VERSION
    value: "11"

steps:
  - task: Maven@3
    inputs:
      mavenPomFile: "$(WORKDIR)/pom.xml"
      goals: "test"
      publishJUnitResults: true
      testResultsFiles: "**/surefire-reports/TEST-*.xml"
      javaHomeOption: "JDKVersion"
      jdkVersionOption: "1.$(JAVA_VERSION)"
      mavenVersionOption: "Default"
      mavenOptions: "-Xmx3072m"
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

  - task: CreateWorkItem@1
    displayName: "Create an issue (bug)"
    condition: and(failed(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      workItemType: "Bug"
      title: "Unit Test failure"
      assignedTo: "$(Build.RequestedForId)"
      fieldMappings: |
        System Info=Test details: $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=ms.vss-test-web.build-test-results-tab
      associate: true

  - task: CreatePRCommentTask@1
    displayName: "Create a PR comment"
    condition: and(failed(), eq(variables['Build.Reason'], 'PullRequest'))
    inputs:
      AuthType: "system"
      Comment: |
        ### Unit Test `failure`
        <details>
        <summary>Pipeline details</summary>

        Pipeline name: `$(Build.DefinitionName)`
        Action: `$(Build.Reason)`
        Job: `$(System.JobName)`
        PR: [$(System.PullRequest.PullRequestId)]($(System.PullRequest.SourceRepositoryURI)/pullrequest/$(System.PullRequest.PullRequestId))
        </details>

        Test details: [Run #$(Build.BuildId)]($(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=ms.vss-test-web.build-test-results-tab)
        Pusher: @<$(Build.RequestedForId)>
