trigger:
  - none

pool:
  vmImage: ubuntu-latest

variables:
  - name: WORKDIR
    value: "$(System.DefaultWorkingDirectory)/apis/userprofile"
  - name: NODE_VERSION
    value: "12"

steps:
  - task: NodeTool@0
    displayName: "Setup Node $(NODE_VERSION)"
    inputs:
      versionSpec: "$(NODE_VERSION)"

  # npm ci is similar to npm install, except it's meant to be used in automated environments
  # https://docs.npmjs.com/cli/v7/commands/npm-ci
  - script: npm ci
    displayName: "Install CI dependencies"
    workingDirectory: "$(WORKDIR)"

  - script: npm run test
    displayName: "Run Tests"
    workingDirectory: "$(WORKDIR)"

  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: "JUnit"
      testResultsFiles: "userprofile-report.xml"
      searchFolder: "$(WORKDIR)/reports"
      mergeTestResults: true
      failTaskOnFailedTests: true

  - task: CreateWorkItem@1
    displayName: "Create an issue (bug)"
    condition: and(failed(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      workItemType: "Bug"
      title: "Unit Test failure"
      assignedTo: "$(Build.RequestedForId)"
      fieldMappings: |
        System Info=Test details: $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=ms.vss-test-web.build-test-results-tab
      associate: true

  - task: CreatePRCommentTask@1
    displayName: "Create a PR comment"
    condition: and(failed(), eq(variables['Build.Reason'], 'PullRequest'))
    inputs:
      AuthType: "system"
      Comment: |
        ### Unit Test `failure`
        <details>
        <summary>Pipeline details</summary>

        Pipeline name: `$(Build.DefinitionName)`
        Action: `$(Build.Reason)`
        Job: `$(System.JobName)`
        PR: [$(System.PullRequest.PullRequestId)]($(System.PullRequest.SourceRepositoryURI)/pullrequest/$(System.PullRequest.PullRequestId))
        </details>

        Test details: [Run #$(Build.BuildId)]($(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)&view=ms.vss-test-web.build-test-results-tab)
        Pusher: @<$(Build.RequestedForId)>
